name: Run Court Auction Crawler

on:
    push:
        branches:
            - main # main 브랜치에 푸시 시 실행
    schedule:
        # 매일 12시간마다 실행
        - cron: '0 */12 * * *'

jobs:
    run-crawler:
        runs-on: ubuntu-latest

        env:
            TELEGRAM_BOT_API_KEY: ${{ secrets.TELEGRAM_BOT_API_KEY }}
            TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
            SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        steps:
            # 환경 변수 확인을 위한 디버깅 스텝
            - name: Check environment variables
              run: |
                  if [ -z "$TELEGRAM_BOT_API_KEY" ]; then echo "TELEGRAM_BOT_API_KEY is empty"; fi
                  if [ -z "$TELEGRAM_CHAT_ID" ]; then echo "TELEGRAM_CHAT_ID is empty"; fi
                  if [ -z "$SUPABASE_URL" ]; then echo "SUPABASE_URL is empty"; fi
                  if [ -z "$SUPABASE_KEY" ]; then echo "SUPABASE_KEY is empty"; fi
            # 리포지토리를 체크아웃
            - name: Checkout repository
              uses: actions/checkout@v3

            # Python 환경 설정
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.12' # 원하는 Python 버전 지정

            # 의존성 설치
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            # 크롤러 실행
            - name: Run crawler
              run: python courtauction.py
